### PR TITLE
Ci trigger on pr syncrhonize

### PR DESCRIPTION
**Pull request by belgattitude**
@adrai  a change of mind... as I'm often re-synchronizing my PR, I'd like to run the ci too

### CODE REVIEW

**Comment by belgattitude** [comment]
Sorry for the contributors, I'll remove it in a minute

**Comment by adrai** [comment]
why? you're a contributor now ;-)

**Comment by adrai** [comment]
keep it

**Comment by adrai** [comment]
but the test is failing

**Comment by belgattitude** [comment]
I'm on it

**Comment by adrai** [comment]
master should already be fixed

**Comment by belgattitude** [comment]
Nice.. @adrai is it possible to not merge on master directly ? I'm asking because it's easier for me to track changes

**Comment by adrai** [comment]
already done so

**Pull request merged**
