### PR TITLE
feat: Rendering pages on browser when Instance i18n finished initiali…

### PR DESCRIPTION
**Pull request by zakudriver**
Rendering pages on browser when Instance i18n finished initialization completely.

Rendering pages after loading resources of backend to resolve error `Text content does not match server-rendered HTML` on NEXT.

#### Checklist

- [ ] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [ ] tests are included
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

#### Checklist (for documentation change)

- [ ] only relevant documentation part is changed (make a diff before you submit the PR)
- [x] motivation/reason is provided
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by adrai** [comment]
Can you mention this in the readme?

**Comment by zakudriver** [comment]
The [example](https://github.com/i18next/next-i18next/blob/master/examples/auto-static-optimize/pages/auto-static.tsx).

**Comment by zakudriver** [comment]
To deal with the error happens on example [/auto-static](https://github.com/i18next/next-i18next/blob/master/examples/auto-static-optimize/pages/auto-static.tsx)

**Comment by adrai** [comment]
which error? is there an issue? can you provide the link to the github issue?

**Comment by adrai** [comment]
btw: you have also some build errors: https://github.com/i18next/next-i18next/actions/runs/12176576574/job/33962675076?pr=2306

**Comment by adrai** [comment]
@NamPNQ can you review and have a look at this? It's your example ;-)
@zakudriver fix this: https://github.com/i18next/next-i18next/actions/runs/12176576574/job/33962675076?pr=2306

**Comment by adrai** [comment]
btw: your change will remove that warning, but will introduce this warning: "react-i18next:: You will need to pass in an i18next instance by using initReactI18next Error Component Stack"

**Comment by NamPNQ** [comment]
@zakudriver Can you update the example too?

From your code

```
    const [ready, setReady] = useState<boolean>(
      !configOverride?.clientAwaitInit
    )
```

If we set `clientAwaitInit = true`, so the server side don't translated? And I think it's not the target for auto-static, it should translate on server-side too

**Comment by zakudriver** [comment]
Yeah. You are right, I will close this pr. thx. ;)

**Pull request closed without merging**
