### PR TITLE
feat: support i18next v22 type augmentation

### PR DESCRIPTION
**Pull request by belgattitude**
Change example to support the new i18next v22 types augmentation. 

To update look at https://github.com/i18next/next-i18next/pull/1997/files#diff-53f0261e2e3a0e94c11e361fb2729a6d2995921dca99da95aa77209f66226156

### CODE REVIEW

**Comment by belgattitude** [comment]
## Issue

Type checks are lost when reworking the types from 'react-i18next.d.ts' to 'i18next.d.ts'

image

**Comment by belgattitude** [comment]
I'll debug tomorrow, but any help appreciated

links to keep an eye on (by @adrai)

- https://github.com/i18next/i18next/pull/1853#issuecomment-1291566329

**Comment by adrai** [comment]
@pedrodurek any chance to help @belgattitude  with this?

**Comment by pedrodurek** [comment]
Sorry guys, It's been a tough week. I'll have some time tomorrow to look into it.

**Comment by pedrodurek** [comment]
Hey @belgattitude, that's happening because `next-i18next@12.1.0` is relying on the old `react-i18next` and `18next` versions. https://github.com/i18next/next-i18next/blob/v12.1.0/package.json#L132-L144

**Comment by adrai** [comment]
> Hey @belgattitude, that's happening because `next-i18next@12.1.0` is relying on the old `react-i18next` and `18next` versions. https://github.com/i18next/next-i18next/blob/v12.1.0/package.json#L132-L134
> 
> cc: @adrai 
12.1 is the npm released version, but on master everything is up-to-date @pedrodurek

**Comment by pedrodurek** [comment]
Once we create a new version for `next-i18next` based `master`, the types will work. Alternatively, we can add npm override for `next-18next` 
```json
"overrides": {
  "next-i18next": {
    "react-i18next": "12.0.0",
    "i18next": "22.0.3"
  }
}
```

**Comment by adrai** [comment]
> Once we create a new version for `next-i18next` based `master`, the types will work. Alternatively, we can add npm override for `next-18next`
> 
> ```json
> "overrides": {
>   "next-i18next": {
>     "react-i18next": "12.0.0",
>     "i18next": "22.0.3"
>   }
> }
> ```

@belgattitude can you check that overrides?

**Comment by adrai** [comment]
@belgattitude as soon as you think we're ready for releasing, let me know... probably still waiting for this #1998 ?

**Comment by belgattitude** [comment]
Cool, gonna check tomorrow.  Make sense

**Comment by pedrodurek** [comment]
Screenshot 2022-11-05 at 10 15 12 AM

**Comment by belgattitude** [comment]
Works like a charm :+1: 

> as soon as you think we're ready for releasing, let me know... probably still waiting for this https://github.com/i18next/next-i18next/pull/1998 ?

@adrai regarding #1998, I'd like to have an hour tomorrow to test typescript 4.9-rc before merging.

**Review by pedrodurek — APPROVED** [review]
Looks great to me!

**Pull request merged**
