### PR TITLE
Upgrading: clarify keys typings update

### PR DESCRIPTION
**Pull request by belgattitude**
In the light of https://github.com/i18next/next-i18next/discussions/2029.

@adrai I would like to release the v13.0.0, what's your feeling about it ? 

PS: The only thing was: https://github.com/i18next/next-i18next/pull/2018#issuecomment-1313565603 but I guess we can go on.

### CODE REVIEW

**Comment by adrai** [comment]
lgtm...
let me know when ready to publish...

**Comment by belgattitude** [comment]
Great, let's make it happen :smile:

**Comment by adrai** [comment]
will publish it now...

**Comment by adrai** [comment]
v13 should be published

**Comment by adrai** [comment]
fyi: 
image

**Comment by belgattitude** [comment]
Oh thank you

**Comment by belgattitude** [comment]
Updated my own examples. Run smooth til now

**Pull request merged**
