### PR TITLE
Update serverSideTranslation args type

### PR DESCRIPTION
**Pull request by mayone-du**
Thanks for developing a great library!

The `useTranslation` function completes the namespace defined in `CustomTypeOptions` on `i18next.d.ts`, but the `serverSideTranslations` function does not, so I changed the type.

(If the change causes any inconvenience, close this PR.)

#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [x] tests are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by adrai** [comment]
Why is that change necessary?
Is there an issue?

**Comment by mayone-du** [comment]
The reason is that the argument passed when executing `getServerSideTranslations` is not type safe.
This is not in the issue, but I created a PR because I was unhappy with it while using it.

**Comment by adrai** [comment]
I'm not a TS expert, but I don't think `Namespace[number]` is correct, @pedrodurek @belgattitude?

**Comment by mayone-du** [comment]
Since the original Namespace type definition is T | T[], Namespace[number] narrows it down to T.

(T contains namespace if it is defined, or a string if not.)

**Comment by adrai** [comment]
included in v13.2.0

**Pull request merged**
